development:
  adapter: mysql2
  pool: 5
  timeout: 5000
  database: studio_dev
  username: root
  password: 'frogger88'
test:
  adapter: mysql2
  pool: 5
  timeout: 5000
  database: studio_test
  username: root
  password: 'frogger88'
production:
  adapter: mysql2
  database: studio_production
  pool: 5
  timeout: 5000
  host: localhost
  username: <%= Rails.application.secrets[:database][:username] %>
  password: <%= Rails.application.secrets[:database][:password] %>